#  ______                        _____ _
# |  ____|                      / ____| |
# | |__ __ _ _ __   ___ _   _  | |  __| | _____      __
# |  __/ _` | '_ \ / __| | | | | | |_ | |/ _ \ \ /\ / /
# | | | (_| | | | | (__| |_| | | |__| | | (_) \ V  V /
# |_|  \__,_|_| |_|\___|\__, |  \_____|_|\___/ \_/\_/
#                        __/ |
#                        |___/

# Useful links:
# Documentation: https://hhitt-1.gitbook.io/fancy-glow-documentation
# Discord for support, suggestions & more: https://discord.com/invite/6SgzfJFVwq
# MiniMessage tool to preview changes: https://webui.advntr.dev/

# DO NOT CHANGE THIS.
config-version: 6

# Should selected glow mode persist when a player leaves the server?
Persistent_Mode: true

# Rainbow mode update interval
# 1 second = 20 ticks, Keep in mind when using low values it might affect performance.
Rainbow_Update_Interval: 10

# Flashing mode update interval
# 1 second = 20 ticks, Keep in mind when using low values it might affect performance.
Flashing_Update_Interval: 6

# Change to false if you want to use a menu plugin to handle your glow.
Open_Glow_Menu: true

# Use flash mode when player is also using rainbow mode.
# If you experience problems when using this option please notify plugin developers.
Flash_Rainbow: false

# Notify players with permission and the server if player has an available update.
Notify_Updates: true

# This option only works if TAB v5.0.4 by NEZNAMY is on the server.
# This will automatically set the player tag prefix to use the glow placeholder.
Auto_Tag: false

Messages:
  # Traducción de todos los mensajes del plugin
  No_Permission: "<red>¡No tienes permiso para hacer esto!"
  Reload_Message: "<blue>¡Configuración del plugin recargada correctamente!"
  Enable_Glow: "<green>¡Brillo activado correctamente!"
  Disable_Glow: "<red>¡Brillo desactivado correctamente!"
  Enable_Flashing: "<green>¡Modo destellante activado!"
  Disable_Flashing: "<red>¡Modo destellante desactivado!"
  Enable_Rainbow: "<green>¡Modo arcoíris activado!"
  Disable_Rainbow: "<red>¡Modo arcoíris desactivado!"
  Disable_Usage: "<red>¡Uso incorrecto! Usa /glow disable <jugador>."
  Disable_Glow_Others: "<red>¡Brillo de %player_name% desactivado!"
  Disable_Glow_Everyone: "<red>¡Brillo de todos los jugadores en línea desactivado!"
  Not_Glowing: "<red>¡No estás brillando actualmente!"
  Not_Valid_Color: "<red>¡Color de brillo no válido!"
  Color_Command_Usage: "<red>¡Uso incorrecto! Usa /glow color <color>."
  Color_Set_Command_Usage: "<red>¡Uso incorrecto! Usa /glow set <jugador> <color>."
  Unknown_Target: "<red>¡El jugador %player_name% no está en línea!"
  Target_Not_Glowing: "<red>¡El jugador objetivo no está brillando!"
  Invalid_Sub_Command: "<red>Subcomando desconocido \"%sub_command%\"."
  Color_Already_Selected: "<red>Ya tienes ese color seleccionado."
  Flashing_With_Rainbow: "<red>Combinar arcoíris y destellante está desactivado."
  # Mensaje que recibe el jugador al entrar a un mundo donde el brillo está desactivado
  Disabled_World_Message: "<red>¡El brillo está desactivado en este mundo!"
  # Traducciones para el placeholder de estado (%fancyglow_status_formatted%)
  Glow_Status_False: "<red>¡Sin brillo! ❌"
  Glow_Status_True: "<green>¡Brillando! ✔</green>"
  Glow_Status_None: "NINGUNO"
  # Uso interno.
  Message_Not_Found: "Mensaje no encontrado en el enum de mensajes."

# List of worlds where glow cannot be enabled
Disabled_Worlds:
  - "Example"
  - "DisabledGlowWorld"

Inventory:
  # Para traducir el menú
  Title: "<dark_red>¡Selecciona un color de brillo!"
  Items:
    Red_Glow_Name: "<red>Rojo</red>"
    Gold_Glow_Name: "<gold>Dorado</gold>"
    Blue_Glow_Name: "<blue>Azul</blue>"
    Aqua_Glow_Name: "<aqua>Agua</aqua>"
    Green_Glow_Name: "<green>Verde</green>"
    White_Glow_Name: "<white>Blanco</white>"
    Yellow_Glow_Name: "<yellow>Amarillo</yellow>"
    Gray_Glow_Name: "<color:#bdbdbd>Gris</color>"
    Black_Glow_Name: "<color:#454545>Negro</color>"
    Dark_Red_Glow_Name: "<dark_red>Rojo Oscuro</dark_red>"
    Pink_Glow_Name: "<light_purple>Rosa</light_purple>"
    Purple_Glow_Name: "<dark_purple>Morado</dark_purple>"
    Dark_Aqua_Glow_Name: "<dark_aqua>Agua Oscura</dark_aqua>"
    Dark_Blue_Glow_Name: "<dark_blue>Azul Oscuro</dark_blue>"
    Dark_Gray_Glow_Name: "<color:#919191>Gris Oscuro</color>"
    Dark_Green_Glow_Name: "<dark_green>Verde Oscuro</dark_green>"
    Color_Lore: "<color:#737373>¡Clic para seleccionar!</color>"
  Filler:
    Enabled: true
    Material: "GRAY_STAINED_GLASS_PANE"
    Name: "<rainbow>¡Clic en un color!</rainbow>"
  Status:
    Slot: 41
    Name: "<color:#6effa3>Tu estado de brillo:</color>"
    Lore:
      Selected:
        - "<white>Tienes seleccionado el brillo %mode%."
        - "<gray>¡Clic para desactivar!"
      Click:
        - "<white>¡Selecciona un color de brillo!"
  Rainbow:
    Slot: 39
    Name: "<rainbow>¡Modo Arcoíris!</rainbow>"
    Lore:
      - "<#9e8fff>¡Clic para activar el modo arcoíris!</#9e8fff>"
    Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTI0OTMyYmI5NDlkMGM2NTcxN2IxMjFjOGNkOWEyMWI2OWU4NmMwZjdlMzQyMWFlOWI4YzY0ZDhiOTkwZWI2MCJ9fX0"
  Flashing:
    Slot: 40
    Name: "<gradient:#d6d6d6:#b6b6b6:#9f9f9f:#ececec>¡Modo Destellante!</gradient>"
    Lore:
      - "<#9e8fff>¡Clic para activar el modo destellante!</#9e8fff>"
    Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTFjNTgxYThiNTk3NjkyYjViOTRkM2I4YmViOWM1MmY1Njk5OWQ2MmY3Mzk1NjY4ZmFjNTdhYzk1MmZlNGRjNCJ9fX0="

COMMAND_MANAGER:
  USAGE:
    HEADER: "<color:#9042f5> <bold>FancyGlow</bold> <gray>‣ <white><required> [optional]"
    MESSAGE: "<red>¡Uso de comando inválido!"
    PREFIX: "<red> "